version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gezondheidsmeter_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./apache-config:/etc/apache2/sites-available
    depends_on:
      - db
    networks:
      - gezond_network
    environment:
      - DB_HOST=db
      - DB_NAME=gezondheidsmeter
      - DB_USER=gezond_user
      - DB_PASSWORD=gezond_pass

  db:
    image: mariadb:10.11
    container_name: gezondheidsmeter_db
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=gezondheidsmeter
      - MYSQL_USER=gezond_user
      - MYSQL_PASSWORD=gezond_pass
    networks:
      - gezond_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gezondheidsmeter_phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_USER=gezond_user
      - PMA_PASSWORD=gezond_pass
    networks:
      - gezond_network

volumes:
  db_data:

networks:
  gezond_network:
    driver: bridge
